#!/usr/bin/env node
// Copies pre-built third-party assets (htmx, Leaflet, three self-hosted
// webfonts) out of node_modules into webui/static/vendor/ so base.html can
// reference them locally instead of a CDN - this project's data/log/account
// state already stays off third-party infrastructure, and this keeps the
// static assets consistent with that. Only ever runs at `npm run build`
// (Docker's assets build stage, or a local dev build) - never at runtime.
import { mkdirSync, copyFileSync, readFileSync, writeFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const NODE_MODULES = join(ROOT, "node_modules");
const VENDOR = join(ROOT, "webui", "static", "vendor");

function ensureDir(path) {
  mkdirSync(path, { recursive: true });
}

function copy(from, to) {
  ensureDir(dirname(to));
  copyFileSync(from, to);
}

// --- htmx ---
copy(join(NODE_MODULES, "htmx.org", "dist", "htmx.min.js"), join(VENDOR, "htmx.min.js"));

// --- Leaflet ---
// dist/leaflet.js is already the minified production build (dist/leaflet-src.js
// is the unminified, source-mapped one) - confirmed by file size, not naming.
copy(join(NODE_MODULES, "leaflet", "dist", "leaflet.js"), join(VENDOR, "leaflet.min.js"));
copy(join(NODE_MODULES, "leaflet", "dist", "leaflet.css"), join(VENDOR, "leaflet.min.css"));
const leafletImagesDir = join(NODE_MODULES, "leaflet", "dist", "images");
for (const file of readdirSync(leafletImagesDir)) {
  copy(join(leafletImagesDir, file), join(VENDOR, "images", file));
}

// --- Fonts (self-hosted via @fontsource, latin subset only) ---
// Each entry is one @fontsource package + the specific latin weight/style
// files this design actually uses (see app.css's --font-display/--font-body/
// --font-mono stacks) - not the full family, to keep the vendored payload
// small.
const FONT_FACES = [
  { pkg: "sora", files: ["latin-600", "latin-700"] },
  { pkg: "figtree", files: ["latin-400", "latin-500", "latin-600", "latin-400-italic"] },
  { pkg: "jetbrains-mono", files: ["latin-400", "latin-500"] },
];

let fontsCss = "/* Generated by scripts/copy-vendor.mjs - do not edit by hand. */\n";
for (const { pkg, files } of FONT_FACES) {
  const pkgDir = join(NODE_MODULES, "@fontsource", pkg);
  const outFontsDir = join(VENDOR, "fonts", pkg);
  for (const name of files) {
    const cssPath = join(pkgDir, `${name}.css`);
    let css = readFileSync(cssPath, "utf8");
    // Rewrite each face's own-directory relative url(./files/x.woff2) to the
    // vendored path base.html's <link> will actually be served from, and
    // copy the referenced binary alongside it.
    css = css.replace(/url\(\.\/files\/([^)]+)\)/g, (_match, fontFile) => {
      copy(join(pkgDir, "files", fontFile), join(outFontsDir, fontFile));
      return `url(./fonts/${pkg}/${fontFile})`;
    });
    fontsCss += css + "\n";
  }
}
ensureDir(VENDOR);
writeFileSync(join(VENDOR, "fonts.css"), fontsCss);

console.log("Vendored htmx, Leaflet, and fonts into webui/static/vendor/");
